pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install') {
            steps {
                 bat 'cd Jenkins-CI & npm install'
            }
        }
        stage('Checks') {
            retry(2)
            steps {
                parallel(
                    test: {bat 'cd Jenkins-CI &  npm test'},
                    lint: {bat 'cd Jenkins-CI & npm run lint'}
                )
                
            }
        }

    }
    post {
        always {
            slackSend( 
                message: "Build ${env.BUILD_NUMBER} ${currentBuild.result}",
                color: currentBuild.result == 'SUCCESS' ? 'good' : 'danger' 
            )
        }

    }
}